#!/bin/bash
MINLOGEL="---MINLOGPATH---/minlog.el"
MINLOGTITEL="MINLOG"
WINDOWTITEL=$MINLOGTITEL:$1

# Which Emacs to use
if [ -z $EMACS ]; then
    EMACS="emacs";
fi

# Starting MINLOG
if [ -z $FONTSET ]; then
    $EMACS -i -title $WINDOWTITEL -l $MINLOGEL $1
else
    $EMACS -fn $FONTSET -i -title $WINDOWTITEL -l $MINLOGEL $1;
fi
