#!/bin/bash
MINLOGEL="---MINLOGPATH---/minlog.el"

# Which Emacs to use
if [ -z $EMACS ]; then
    EMACS="emacs";
fi

if [ -z "$1" ]; then
    RUNMINLOG="(run-minlog)";
else
    RUNMINLOG="(run-minlog \"$1\")";
fi

# Starting MINLOG
if [ -z $FONTSET ]; then
    $EMACS -i -l $MINLOGEL --exec "$RUNMINLOG"
else
    $EMACS -fn $FONTSET -i -l $MINLOGEL --exec "$RUNMINLOG";
fi
